### ISSUE TITLE
Question about C4 dataset

### ISSUE THREAD

**Issue by abcbdf** [AIoT-MLSys-Lab/SVD-LLM#10]
Hello, thanks for this great project. I found:
`    
 test_data = load_dataset("json", data_files="utils/c4-validation.json")['train']
`
 in the code but there is no "utils/c4-validation.json" file. Where should I find this?

**Comment by tuidan** [comment]
Hi, we use the same c4 dataset as in [SparseGPT](https://github.com/IST-DASLab/sparsegpt). Since the original dowload link is invalid, please directly download it from this [link](https://drive.google.com/drive/folders/123Id1MkZVsKySGy_sMO4RgiJKrtPcvUp?usp=sharing) and add the two json files under the `utils/.` folder.

**Comment by abcbdf** [comment]
@tuidan Thanks a lot for your fast reply. By the way, in table 1 of the article, do all methods use same callibration dataset wikitext or each dataset's ppl is test with using itself as callibration dataset?

**Comment by tuidan** [comment]
Yes, they all use the same callibration dataset wikitext.

**Comment by abcbdf** [comment]
@tuidan Thanks!
